language: c

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y gobjc
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt-get install gcc-5 g++-5
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

        script:
                - cd tests/
                - make
                - cd build/
                - ./tests
